### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by kaiwinter**
Translated all terms and added link in the HTML file.

### CODE REVIEW

**Comment by ndp** [comment]
Thank you!!!

**Comment by ndp** [comment]
Viel Dank!

**Comment by kaiwinter** [comment]
I noticed that you have updated the Cheat Sheet on the NDP domain already but haven't merged this pull request. Was this intentional?

**Comment by ndp** [comment]
I just forgot the push. Sorry about that. All better now.

**Pull request merged**
