### PR TITLE
Add Traditional Chinese translation and Update README file.

### PR DESCRIPTION
**Pull request by Hsins**
FYI

- Add Traditional Chinese translation.
- Update README file for inserting screenshot and change hyperlink in HTML with Markdown syntax.

### CODE REVIEW

**Comment by ndp** [comment]
Thank you! I'm going to get to this soon.... I have to polish off another project first.

**Comment by ndp** [comment]
Merged manually.

Having all the formatting changes combined with the new code makes a comparison of the changes difficult or impossible. I just copied the one group of language translations into the array of languages, and then separately did a reformat on the file.

**Comment by ndp** [comment]
Again, thank you!

**Comment by waldyrious** [comment]
For future reference:

- 207f6ebbc9 from this PR (CN translation) was added as 8e67f2382d and dbcf3a340c on master
- 56e7c7f1d7 from this PR (README changes) was added as 0fa8810be9 on master

**Pull request closed without merging**
